(function () {
    'use strict';

    angular.module('ariaNg').config(['$translateProvider', function ($translateProvider) {
        $translateProvider.translations('zh-CN', {
            'Simplified Chinese': '简体中文',
            'New': '新建',
            'Start': '开始下载任务',
            'Pause': '暂停下载任务',
            'Delete': '删除下载任务',
            'Display Order': '显示顺序',
            'Default': '默认',
            'By File Name': '按文件名',
            'By File Size': '按文件大小',
            'By Completed Percent': '按进度',
            'By Remain Time': '按剩余时间',
            'By Download Speed': '按下载速度',
            'Download': '下载',
            'Downloading': '正在下载',
            'Waiting': '正在等待',
            'Downloaded / Stopped': '已完成 / 已停止',
            'Settings': '系统设置',
            'AriaNg Settings': 'AriaNg 设置',
            'Aria2 Settings': 'Aria2 设置',
            'Basic Settings': '基本设置',
            'BitTorrent Settings': 'BitTorrent 设置',
            'RPC Settings': 'RPC 设置',
            'Advanced Settings': '高级设置',
            'Aria2 Status': 'Aria2 状态',
            'File Name': '文件名',
            'File Size': '大小',
            'Completed Percent': '进度',
            'Remain Time': '剩余时间',
            'Download Speed': '下载速度',
            'Files': '个文件',
            'Language': '语言',
            'Aria2 RPC Host': 'Aria2 RPC 主机',
            'Aria2 RPC Port': 'Aria2 RPC 端口',
            'Aria2 RPC Protocol': 'Aria2 RPC 协议',
            'Global Stat Refresh Interval': '全局状态刷新间隔',
            'Download Task Refresh Interval': '下载任务刷新间隔',
            'Aria2 Version': 'Aria2 版本',
            'Enabled Features': '已启用的功能',
            'Toggle Navigation': '切换导航',
            'Loading': '正在加载...',
            'More Than One Day': '超过1天',
            'Unknown': '未知',
            'Seconds': '秒',
            'Milliseconds': '毫秒',
            '(0 is disabled)': '(0为禁用)',
            'Changes to the settings take effect after refreshing page.': '设置将在页面刷新后生效.'
        });
    }])
})();
