name: Build Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install
          npm install -g gulp

      - name: Build all-in-one version
        run: |
          gulp clean build-bundle

      - name: Package all-in-one version
        run: |
          mkdir -p release-files
          cd dist
          zip -r -9 "../release-files/AriaNg-${GITHUB_REF_NAME}-AllInOne.zip" .

      - name: Build standard version
        run: |
          gulp clean build

      - name: Package standard version
        run: |
          mkdir -p release-files
          cd dist
          zip -r -9 "../release-files/AriaNg-${GITHUB_REF_NAME}.zip" .

      - name: Publish Release ${{ github.ref_name }}
        uses: softprops/action-gh-release@v3
        with:
          name: AriaNg ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ./release-files/*.zip
          draft: true
