#!/usr/bin/with-contenv bash

printf "${CUSTOM_RPC_TOKEN:-$(openssl rand -base64 32)}" > /var/run/s6/container_environment/RPC_TOKEN

OVERRIDE_OPTIONS=("${CUSTOM_OVERRIDE_OPTIONS}")

if [ "${#OVERRIDE_OPTIONS[@]}" -gt 0 ]; then
  printf "${OVERRIDE_OPTIONS}" > /var/run/s6/container_environment/OVERRIDE_OPTIONS
else
  unset OVERRIDE_OPTIONS
fi

touch /data/config/custom.conf

chown -R abc:abc \
         /data/aria2c-webui \
         /data/config \
         /data/downloads

chown -R abc:abc  \
        /var/lib/nginx

echo "RPC Token: $(cat /var/run/s6/container_environment/RPC_TOKEN)"
